{% set name = "yggdrasil-python-rapidjson" %}
{% set version = "1.1.0" %}
# {% set version = os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG %}
{% set PY_VER_MAJOR = PY_VER.split('.')[0] %}
{% set PY_VER_MINOR = PY_VER.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - hatch-fancy-pypi-readme
    - numpy
    - scikit-build-core
    - setuptools_scm
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - rapidjson
  requires:
    - pandas
    - pytest
    - pytz
    - trimesh
    - unyt
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around YggdrasilRapidJSON.
  description: |
    A Python wrapper around YggdrasilRapidJSON. YggdrasilRapidJSON is a
    header-only C++ library for JSON operation extended for use with
    yggdrasil
  # doc_url: 
  dev_url: https://github.com/cropsinsilico/yggdrasil-python-rapidjson

extra:
  recipe-maintainers:
    - langmm
