{% set name = "yggdrasil-python-rapidjson" %}
{% set python_name = "yggdrasil_python_rapidjson" %}
{% set version = "1.21.0.1" %}
# {% set version = os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG %}
{% set PY_VER_MAJOR = PY_VER.split('.')[0] %}
{% set PY_VER_MINOR = PY_VER.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/${{ name }}/${{ name }}/${{ python_name }}-v${{ version }}.tar.gz
  # sha256: 
  path: ../

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --config-settings=cmake.define.RAPIDJSON_INCLUDE_DIRS=rapidjson/include '  # [unix]
  script: 'set "SKBUILD_CMAKE_ARGS=-G Ninja" && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --config-settings=cmake.define.RAPIDJSON_INCLUDE_DIRS=rapidjson/include '  # [win]

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.13.0                         # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cmake >=3.15
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hatch-fancy-pypi-readme
    - numpy >=1.13.0
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
  run:
    - {{ stdlib('c') }}
    - python
    - numpy >=1.13.0

test:
  imports:
    - yggdrasil_rapidjson
  requires:
    - pandas
    - pytest
    - pytz
    - trimesh
    - unyt
  source_files:
    - tests
    - rapidjson/test/example_python.py
  commands:
    - pytest -sv tests

about:
  home: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around YggdrasilRapidJSON.
  description: |
    A Python wrapper around YggdrasilRapidJSON. YggdrasilRapidJSON is a
    header-only C++ library for JSON operation extended for use with
    yggdrasil
  doc_url: https://cropsinsilico.github.io/yggdrasil-python-rapidjson/
  dev_url: https://github.com/cropsinsilico/yggdrasil-python-rapidjson

extra:
  recipe-maintainers:
    - langmm
