context:
  name: "yggdrasil-python-rapidjson"
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../

build:
  number: 0
  script: '${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - hatch-fancy-pypi-readme
    - numpy
    - scikit-build-core
    - setuptools_scm
  host:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - hatch-fancy-pypi-readme
    - numpy
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
  run:
    - ${{ stdlib('c') }}
    - python
    - numpy

tests:
  - python:
      imports:
        - yggdrasil_rapidjson
  - script:
      - pytest -sv tests
    requirements:
      run:
        - pandas
        - pytest
        - pytz
        - trimesh
        - unyt
    files:
      source:
      - tests/

about:
  homepage: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  repository: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around YggdrasilRapidJSON.
  description: |
    A Python wrapper around YggdrasilRapidJSON. YggdrasilRapidJSON is a
    header-only C++ library for JSON operation extended for use with
    yggdrasil
  # documentation:

extra:
  recipe-maintainers:
    - langmm
