name: Build & test

on:
  push:
    branches-ignore:
     - gh-pages
    tags:
     - '*'
  schedule:
  - cron: 0 10 * * 1
  - cron: 0 10 1 * *

env:
  PYTHONVERSION_STD: "3.11"

jobs:
  tests:
    name: All tests, on current Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python ${{ env.PYTHONVERSION_STD }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHONVERSION_STD }}

      - name: Install dependencies
        run: |
          pip install -v '.[test]'

      - name: Tests
        run: |
          pytest -sv tests

      - name: Doctests
        run: |
          make -C docs doctest -e PYTHON=$(which python3)

      # - name: Typing stub tests
      #   run: |
      #     stubtest rapidjson

  debug-tests:
    name: Memory leak tests, on current debug build Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: deadsnakes/action@v3.2.0
        with:
          python-version: ${{ env.PYTHONVERSION_STD }}
          debug: true

      - name: Install dependencies
        run: |
          pip install --config-settings=cmake.build-type="Debug" --config-settings=cmake.define.YGGDRASIL_RAPIDJSON_CHECK_PYREFS:BOOL=ON -v '.[test]'

      - run: |
          pytest -sv tests

  all_tests_passed:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [tests, debug-tests]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
